{{- if and (not .Values.existingSecret) (or .Values.secrets.sourcePassword .Values.secrets.targetPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "migrate.fullname" . }}
  labels:
    {{- include "migrate.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.sourcePassword }}
  source-password: {{ .Values.secrets.sourcePassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.targetPassword }}
  target-password: {{ .Values.secrets.targetPassword | b64enc | quote }}
  {{- end }}
{{- end }}
